"""empty message

Revision ID: 1055d17033ab
Revises: 9705ccae6dde
Create Date: 2018-04-06 00:34:28.478251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1055d17033ab'
down_revision = '9705ccae6dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstName', sa.String(length=80), nullable=True))
    op.drop_column('users', 'firsName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firsName', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('users', 'firstName')
    # ### end Alembic commands ###
